# Generated by Django 4.2.5 on 2023-10-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='formato',
            field=models.CharField(choices=[('ebook', 'eBook'), ('libro_fisico', 'Libro Físico')], default='libro_fisico', max_length=20),
        ),
    ]
