# Generated by Django 4.2.5 on 2023-10-06 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('premios', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('editorial', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('sinopsis', models.CharField(max_length=40)),
                ('numpag', models.IntegerField()),
                ('aplicativo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('editorial', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('sinopsis', models.CharField(max_length=40)),
                ('numpag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('webpage', models.URLField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('temas', models.CharField(max_length=40)),
                ('numpag', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
