# Generated by Django 4.2.5 on 2023-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1App', '0003_rename_numpag_revista_numero_remove_revista_webpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='biografia',
            field=models.CharField(default='Bio', max_length=200),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(default='autor@correo.com', max_length=40),
        ),
        migrations.AlterField(
            model_name='autor',
            name='premios',
            field=models.CharField(max_length=200),
        ),
    ]
